In [9]:
import pandas as pd
ames_housing = pd.read_csv("../datasets/house_prices.csv", na_values="?")
ames_housing = ames_housing.drop(columns="Id")

target_name = "SalePrice"
data, target = ames_housing.drop(columns=target_name), ames_housing[target_name]
target = (target > 200_000).astype(int)

In [10]:
ames_housing.info()
ames_housing.dtypes.value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSSubClass     1460 non-null   int64
 1   MSZoning       1460 non-null   object
 2   LotFrontage    1201 non-null   float64
 3   LotArea        1460 non-null   int64
 4   Street         1460 non-null   object
 5   Alley          91 non-null     object
 6   LotShape       1460 non-null   object
 7   LandContour    1460 non-null   object
 8   Utilities      1460 non-null   object
 9   LotConfig      1460 non-null   object
 10  LandSlope      1460 non-null   object
 11  Neighborhood   1460 non-null   object
 12  Condition1     1460 non-null   object
 13  Condition2     1460 non-null   object
 14  BldgType       1460 non-null   object
 15  HouseStyle     1460 non-null   object
 16  OverallQual    1460 non-null   int64
 17  OverallCond    1460 non-null   int64
 18  YearBuilt      1460 non-null   int64
 19  YearRemodAdd   1460 non-null   int64
 20  RoofStyle      1460 non-null   object
 21  RoofMatl       1460 non-null   object
 22  Exterior1st    1460 non-null   object
 23  Exterior2nd    1460 non-null   object
 24  MasVnrType     1452 non-null   object
 25  MasVnrArea     1452 non-null   float64
 26  ExterQual      1460 non-null   object
 27  ExterCond      1460 non-null   object
 28  Foundation     1460 non-null   object
 29  BsmtQual       1423 non-null   object
 30  BsmtCond       1423 non-null   object
 31  BsmtExposure   1422 non-null   object
 32  BsmtFinType1   1423 non-null   object
 33  BsmtFinSF1     1460 non-null   int64
 34  BsmtFinType2   1422 non-null   object
 35  BsmtFinSF2     1460 non-null   int64
 36  BsmtUnfSF      1460 non-null   int64
 37  TotalBsmtSF    1460 non-null   int64
 38  Heating        1460 non-null   object
 39  HeatingQC      1460 non-null   object
 40  CentralAir     1460 non-null   object
 41  Electrical     1459 non-null   object
 42  1stFlrSF       1460 non-null   int64
 43  2ndFlrSF       1460 non-null   int64
 44  LowQualFinSF   1460 non-null   int64
 45  GrLivArea      1460 non-null   int64
 46  BsmtFullBath   1460 non-null   int64
 47  BsmtHalfBath   1460 non-null   int64
 48  FullBath       1460 non-null   int64
 49  HalfBath       1460 non-null   int64
 50  BedroomAbvGr   1460 non-null   int64
 51  KitchenAbvGr   1460 non-null   int64
 52  KitchenQual    1460 non-null   object
 53  TotRmsAbvGrd   1460 non-null   int64
 54  Functional     1460 non-null   object
 55  Fireplaces     1460 non-null   int64
 56  FireplaceQu    770 non-null    object
 57  GarageType     1379 non-null   object
 58  GarageYrBlt    1379 non-null   float64
 59  GarageFinish   1379 non-null   object
 60  GarageCars     1460 non-null   int64
 61  GarageArea     1460 non-null   int64
 62  GarageQual     1379 non-null   object
 63  GarageCond     1379 non-null   object
 64  PavedDrive     1460 non-null   object
 65  WoodDeckSF     1460 non-null   int64
 66  OpenPorchSF    1460 non-null   int64
 67  EnclosedPorch  1460 non-null   int64
 68  3SsnPorch      1460 non-null   int64
 69  ScreenPorch    1460 non-null   int64
 70  PoolArea       1460 non-null   int64
 71  PoolQC         7 non-null      object
 72  Fence          281 non-null    object
 73  MiscFeature    54 non-null     object
 74  MiscVal        1460 non-null   int64
 75  MoSold         1460 non-null   int64
 76  YrSold         1460 non-null   int64
 77  SaleType       1460 non-null   object
 78  SaleCondition  1460 non-null   object
 79  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(34), object(43)
memory usage: 912.6+ KB

object     43
int64      34
float64     3
dtype: int64

In [11]:
ames_housing.describe()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,46.549315,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,161.319273,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,0.000000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,0.000000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,1474.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [12]:
ames_housing.shape[1]

80

Numerical features :

In [13]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_validate

numerical_features = [
  "LotFrontage", "LotArea", "MasVnrArea", "BsmtFinSF1", "BsmtFinSF2",
  "BsmtUnfSF", "TotalBsmtSF", "1stFlrSF", "2ndFlrSF", "LowQualFinSF",
  "GrLivArea", "BedroomAbvGr", "KitchenAbvGr", "TotRmsAbvGrd", "Fireplaces",
  "GarageCars", "GarageArea", "WoodDeckSF", "OpenPorchSF", "EnclosedPorch",
  "3SsnPorch", "ScreenPorch", "PoolArea", "MiscVal",
]
data_numeric = data[numerical_features]
model = make_pipeline(StandardScaler(), 
                      SimpleImputer(strategy = "mean"), 
                      LogisticRegression())
cv_results1 = cross_validate(model, data_numeric, target, cv = 5)
scores = cv_results1['test_score']
print(scores.mean())

0.8952054794520548

Add categorical features :

In [14]:
categorical_features = list(set(data.columns) - set(numerical_features))
print(len(numerical_features))
print(len(categorical_features))
print(len(data.columns))
print(categorical_features)

24
55
79
['GarageQual', 'BsmtFinType1', 'YearRemodAdd', 'MSZoning', 'Condition2', 'PoolQC', 'GarageYrBlt', 'GarageFinish', 'BsmtHalfBath', 'MSSubClass', 'LotConfig', 'BsmtExposure', 'Neighborhood', 'YrSold', 'BsmtQual', 'BsmtCond', 'Alley', 'BsmtFullBath', 'LotShape', 'CentralAir', 'SaleCondition', 'LandContour', 'ExterCond', 'Exterior2nd', 'HalfBath', 'BldgType', 'Condition1', 'HouseStyle', 'Heating', 'KitchenQual', 'GarageCond', 'OverallQual', 'GarageType', 'LandSlope', 'ExterQual', 'RoofStyle', 'SaleType', 'OverallCond', 'MasVnrType', 'Exterior1st', 'FullBath', 'Foundation', 'YearBuilt', 'HeatingQC', 'Electrical', 'Fence', 'FireplaceQu', 'Utilities', 'RoofMatl', 'BsmtFinType2', 'MoSold', 'Functional', 'MiscFeature', 'PavedDrive', 'Street']

On teste l'encodage OneHot sans handle unknown :

In [15]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# Cat.
enc = OneHotEncoder()
enc.fit(data[categorical_features])
print(enc.categories_)
# print(enc.get_feature_names())
data_enc = enc.transform(data[categorical_features])
# print(data_enc)

[array(['Ex', 'Fa', 'Gd', 'Po', 'TA', nan], dtype=object), array(['ALQ', 'BLQ', 'GLQ', 'LwQ', 'Rec', 'Unf', nan], dtype=object), array([1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960,
       1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971,
       1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982,
       1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993,
       1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004,
       2005, 2006, 2007, 2008, 2009, 2010]), array(["'C (all)'", 'FV', 'RH', 'RL', 'RM'], dtype=object), array(['Artery', 'Feedr', 'Norm', 'PosA', 'PosN', 'RRAe', 'RRAn', 'RRNn'],
      dtype=object), array(['Ex', 'Fa', 'Gd', nan], dtype=object), array([1900., 1906., 1908., 1910., 1914., 1915., 1916., 1918., 1920.,
       1921., 1922., 1923., 1924., 1925., 1926., 1927., 1928., 1929.,
       1930., 1931., 1932., 1933., 1934., 1935., 1936., 1937., 1938.,
       1939., 1940., 1941., 1942., 1945., 1946., 1947., 1948., 1949.,
       1950., 1951., 1952., 1953., 1954., 1955., 1956., 1957., 1958.,
       1959., 1960., 1961., 1962., 1963., 1964., 1965., 1966., 1967.,
       1968., 1969., 1970., 1971., 1972., 1973., 1974., 1975., 1976.,
       1977., 1978., 1979., 1980., 1981., 1982., 1983., 1984., 1985.,
       1986., 1987., 1988., 1989., 1990., 1991., 1992., 1993., 1994.,
       1995., 1996., 1997., 1998., 1999., 2000., 2001., 2002., 2003.,
       2004., 2005., 2006., 2007., 2008., 2009., 2010.,   nan]), array(['Fin', 'RFn', 'Unf', nan], dtype=object), array([0, 1, 2]), array([ 20,  30,  40,  45,  50,  60,  70,  75,  80,  85,  90, 120, 160,
       180, 190]), array(['Corner', 'CulDSac', 'FR2', 'FR3', 'Inside'], dtype=object), array(['Av', 'Gd', 'Mn', 'No', nan], dtype=object), array(['Blmngtn', 'Blueste', 'BrDale', 'BrkSide', 'ClearCr', 'CollgCr',
       'Crawfor', 'Edwards', 'Gilbert', 'IDOTRR', 'MeadowV', 'Mitchel',
       'NAmes', 'NPkVill', 'NWAmes', 'NoRidge', 'NridgHt', 'OldTown',
       'SWISU', 'Sawyer', 'SawyerW', 'Somerst', 'StoneBr', 'Timber',
       'Veenker'], dtype=object), array([2006, 2007, 2008, 2009, 2010]), array(['Ex', 'Fa', 'Gd', 'TA', nan], dtype=object), array(['Fa', 'Gd', 'Po', 'TA', nan], dtype=object), array(['Grvl', 'Pave', nan], dtype=object), array([0, 1, 2, 3]), array(['IR1', 'IR2', 'IR3', 'Reg'], dtype=object), array(['N', 'Y'], dtype=object), array(['Abnorml', 'AdjLand', 'Alloca', 'Family', 'Normal', 'Partial'],
      dtype=object), array(['Bnk', 'HLS', 'Low', 'Lvl'], dtype=object), array(['Ex', 'Fa', 'Gd', 'Po', 'TA'], dtype=object), array(["'Brk Cmn'", "'Wd Sdng'", "'Wd Shng'", 'AsbShng', 'AsphShn',
       'BrkFace', 'CBlock', 'CmentBd', 'HdBoard', 'ImStucc', 'MetalSd',
       'Other', 'Plywood', 'Stone', 'Stucco', 'VinylSd'], dtype=object), array([0, 1, 2]), array(['1Fam', '2fmCon', 'Duplex', 'Twnhs', 'TwnhsE'], dtype=object), array(['Artery', 'Feedr', 'Norm', 'PosA', 'PosN', 'RRAe', 'RRAn', 'RRNe',
       'RRNn'], dtype=object), array(['1.5Fin', '1.5Unf', '1Story', '2.5Fin', '2.5Unf', '2Story',
       'SFoyer', 'SLvl'], dtype=object), array(['Floor', 'GasA', 'GasW', 'Grav', 'OthW', 'Wall'], dtype=object), array(['Ex', 'Fa', 'Gd', 'TA'], dtype=object), array(['Ex', 'Fa', 'Gd', 'Po', 'TA', nan], dtype=object), array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), array(['2Types', 'Attchd', 'Basment', 'BuiltIn', 'CarPort', 'Detchd', nan],
      dtype=object), array(['Gtl', 'Mod', 'Sev'], dtype=object), array(['Ex', 'Fa', 'Gd', 'TA'], dtype=object), array(['Flat', 'Gable', 'Gambrel', 'Hip', 'Mansard', 'Shed'], dtype=object), array(['COD', 'CWD', 'Con', 'ConLD', 'ConLI', 'ConLw', 'New', 'Oth', 'WD'],
      dtype=object), array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array(['BrkCmn', 'BrkFace', 'None', 'Stone', nan], dtype=object), array(["'Wd Sdng'", 'AsbShng', 'AsphShn', 'BrkComm', 'BrkFace', 'CBlock',
       'CemntBd', 'HdBoard', 'ImStucc', 'MetalSd', 'Plywood', 'Stone',
       'Stucco', 'VinylSd', 'WdShing'], dtype=object), array([0, 1, 2, 3]), array(['BrkTil', 'CBlock', 'PConc', 'Slab', 'Stone', 'Wood'], dtype=object), array([1872, 1875, 1880, 1882, 1885, 1890, 1892, 1893, 1898, 1900, 1904,
       1905, 1906, 1908, 1910, 1911, 1912, 1913, 1914, 1915, 1916, 1917,
       1918, 1919, 1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928,
       1929, 1930, 1931, 1932, 1934, 1935, 1936, 1937, 1938, 1939, 1940,
       1941, 1942, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953,
       1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964,
       1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975,
       1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986,
       1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997,
       1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008,
       2009, 2010]), array(['Ex', 'Fa', 'Gd', 'Po', 'TA'], dtype=object), array(['FuseA', 'FuseF', 'FuseP', 'Mix', 'SBrkr', nan], dtype=object), array(['GdPrv', 'GdWo', 'MnPrv', 'MnWw', nan], dtype=object), array(['Ex', 'Fa', 'Gd', 'Po', 'TA', nan], dtype=object), array(['AllPub', 'NoSeWa'], dtype=object), array(['ClyTile', 'CompShg', 'Membran', 'Metal', 'Roll', 'Tar&Grv',
       'WdShake', 'WdShngl'], dtype=object), array(['ALQ', 'BLQ', 'GLQ', 'LwQ', 'Rec', 'Unf', nan], dtype=object), array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]), array(['Maj1', 'Maj2', 'Min1', 'Min2', 'Mod', 'Sev', 'Typ'], dtype=object), array(['Gar2', 'Othr', 'Shed', 'TenC', nan], dtype=object), array(['N', 'P', 'Y'], dtype=object), array(['Grvl', 'Pave'], dtype=object)]

Le souci `handle_unknown` n'apparaît pas lorsqu'on encode seulement, mais lorsqu'on entraîne également le modèle, car lors des cross validations, certaines catégories peuvent être dans le lot de test mais pas dans le lot d'entraînement

In [16]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# Cat.
onehot_imputer_transformer = make_pipeline(SimpleImputer(strategy = "most_frequent"), OneHotEncoder(handle_unknown="ignore"))

# Num.
scaler_imputer_transformer = make_pipeline(StandardScaler(), SimpleImputer(strategy = "mean"))

# Preproc.
preprocessor = ColumnTransformer(transformers=[
    ("cat-preprocessor", onehot_imputer_transformer, categorical_features),
    ("num-preprocessor", scaler_imputer_transformer, numerical_features)
],
    remainder="passthrough")

# Model
model = make_pipeline(preprocessor, LogisticRegression(max_iter = 500))
cv_results2 = cross_validate(model, data, target, cv = 5)
print(cv_results2['test_score'].mean())

0.9191780821917808

Does the model improve when adding categorical variables ?

In [17]:
print((cv_results2['test_score'].mean() - cv_results1['test_score'].mean()) > (3 * cv_results2['test_score'].std()))

False